apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-zolkdeqw
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-zolkdeqw:abc2ccac3b8da39e24f2444f6329ffee13340073@sha256:5e9a9633ab4695c3696edb1c3fa83962c09e0ffdb5e5090d69573b2637034ace
          name: container-image
